# Generated by Django 3.0 on 2020-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiocategory',
            old_name='adult',
            new_name='is_adult',
        ),
        migrations.RemoveField(
            model_name='radiocategory',
            name='thumbnail_autogenerated',
        ),
        migrations.RemoveField(
            model_name='radiochannel',
            name='max_recording_time',
        ),
        migrations.RemoveField(
            model_name='radiochannel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='EPG_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='description',
            field=models.TextField(default='default string'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiocategory',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='radiochannel',
            name='category',
        ),
        migrations.AddField(
            model_name='radiochannel',
            name='category',
            field=models.ManyToManyField(related_name='radio_category', to='radio.RadioCategory'),
        ),
        migrations.AlterField(
            model_name='radiochannel',
            name='channel_image',
            field=models.FileField(upload_to=''),
        ),
    ]
